# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ThingSpaceConnectivityManagementApi
  class Configuration
    # The base Uri for API calls
    @base_uri = 'https://example.com/api/m2m/v1'

    @api_key = 'TODO: Replace'

    # create the getters and setters
    class << self
      attr_accessor :base_uri
      attr_accessor :api_key
    end
  end
end
