# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ThingSpaceConnectivityManagementApi
  class ThingSpaceConnectivityManagementAPIClient
    # Singleton access to sms controller
    # @return [SmsController] Returns the controller instance
    def sms
      SmsController.instance
    end

    # Singleton access to session controller
    # @return [SessionController] Returns the controller instance
    def session
      SessionController.instance
    end

    # Singleton access to plans controller
    # @return [PlansController] Returns the controller instance
    def plans
      PlansController.instance
    end

    # Singleton access to leads controller
    # @return [LeadsController] Returns the controller instance
    def leads
      LeadsController.instance
    end

    # Singleton access to groups controller
    # @return [GroupsController] Returns the controller instance
    def groups
      GroupsController.instance
    end

    # Singleton access to devices controller
    # @return [DevicesController] Returns the controller instance
    def devices
      DevicesController.instance
    end

    # Singleton access to callbacks controller
    # @return [CallbacksController] Returns the controller instance
    def callbacks
      CallbacksController.instance
    end

    # Initializer with authentication and configuration parameters
    def initialize(api_key: nil)
      Configuration.api_key = api_key
    end
  end
end
