# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ThingSpaceConnectivityManagementApi
  class AddDevicesResponseMessage < BaseModel
    # TODO: Write general description for this method
    # @return [List of DeviceId]
    attr_accessor :device_ids

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :response

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["device_ids"] = "deviceIds"
        @hash["response"] = "response"
      end
      @hash
    end

    def initialize(device_ids = nil,
                   response = nil)
      @device_ids = device_ids
      @response = response
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        # Parameter is an array, so we need to iterate through it
        device_ids = nil
        if hash["deviceIds"] != nil
          device_ids = Array.new
          hash["deviceIds"].each{|structure| device_ids << (DeviceId.from_hash(structure) if structure)}
        end
        response = hash["response"]

        # Create object from extracted values
        AddDevicesResponseMessage.new(device_ids,
                                      response)
      end
    end
  end
end
