# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ThingSpaceConnectivityManagementApi
  class Address < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :address_line_1

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :address_line_2

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :city

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :country

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :state

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :zip

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["address_line_1"] = "addressLine1"
        @hash["address_line_2"] = "addressLine2"
        @hash["city"] = "city"
        @hash["country"] = "country"
        @hash["state"] = "state"
        @hash["zip"] = "zip"
      end
      @hash
    end

    def initialize(address_line_1 = nil,
                   address_line_2 = nil,
                   city = nil,
                   country = nil,
                   state = nil,
                   zip = nil)
      @address_line_1 = address_line_1
      @address_line_2 = address_line_2
      @city = city
      @country = country
      @state = state
      @zip = zip
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        address_line_1 = hash["addressLine1"]
        address_line_2 = hash["addressLine2"]
        city = hash["city"]
        country = hash["country"]
        state = hash["state"]
        zip = hash["zip"]

        # Create object from extracted values
        Address.new(address_line_1,
                    address_line_2,
                    city,
                    country,
                    state,
                    zip)
      end
    end
  end
end
