# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ThingSpaceConnectivityManagementApi
  class Callback < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :account_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :password

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :service_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :url

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :username

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["account_name"] = "accountName"
        @hash["password"] = "password"
        @hash["service_name"] = "serviceName"
        @hash["url"] = "url"
        @hash["username"] = "username"
      end
      @hash
    end

    def initialize(account_name = nil,
                   password = nil,
                   service_name = nil,
                   url = nil,
                   username = nil)
      @account_name = account_name
      @password = password
      @service_name = service_name
      @url = url
      @username = username
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        account_name = hash["accountName"]
        password = hash["password"]
        service_name = hash["serviceName"]
        url = hash["url"]
        username = hash["username"]

        # Create object from extracted values
        Callback.new(account_name,
                     password,
                     service_name,
                     url,
                     username)
      end
    end
  end
end
