# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ThingSpaceConnectivityManagementApi
  class CallbackActionResponse < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :account_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :service_name

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["account_name"] = "accountName"
        @hash["service_name"] = "serviceName"
      end
      @hash
    end

    def initialize(account_name = nil,
                   service_name = nil)
      @account_name = account_name
      @service_name = service_name
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        account_name = hash["accountName"]
        service_name = hash["serviceName"]

        # Create object from extracted values
        CallbackActionResponse.new(account_name,
                                   service_name)
      end
    end
  end
end
