# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ThingSpaceConnectivityManagementApi
  class CarrierActionsRequest < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :account_name

    # TODO: Write general description for this method
    # @return [List of KvPair]
    attr_accessor :custom_fields

    # TODO: Write general description for this method
    # @return [List of DeviceList]
    attr_accessor :devices

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :group_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :service_plan

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["account_name"] = "accountName"
        @hash["custom_fields"] = "customFields"
        @hash["devices"] = "devices"
        @hash["group_name"] = "groupName"
        @hash["service_plan"] = "servicePlan"
      end
      @hash
    end

    def initialize(account_name = nil,
                   custom_fields = nil,
                   devices = nil,
                   group_name = nil,
                   service_plan = nil)
      @account_name = account_name
      @custom_fields = custom_fields
      @devices = devices
      @group_name = group_name
      @service_plan = service_plan
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        account_name = hash["accountName"]
        # Parameter is an array, so we need to iterate through it
        custom_fields = nil
        if hash["customFields"] != nil
          custom_fields = Array.new
          hash["customFields"].each{|structure| custom_fields << (KvPair.from_hash(structure) if structure)}
        end
        # Parameter is an array, so we need to iterate through it
        devices = nil
        if hash["devices"] != nil
          devices = Array.new
          hash["devices"].each{|structure| devices << (DeviceList.from_hash(structure) if structure)}
        end
        group_name = hash["groupName"]
        service_plan = hash["servicePlan"]

        # Create object from extracted values
        CarrierActionsRequest.new(account_name,
                                  custom_fields,
                                  devices,
                                  group_name,
                                  service_plan)
      end
    end
  end
end
