# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ThingSpaceConnectivityManagementApi
  class CarrierActivateRequest < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :account_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :carrier_ip_pool_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :carrier_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :cost_center_code

    # TODO: Write general description for this method
    # @return [List of KvPair]
    attr_accessor :custom_fields

    # TODO: Write general description for this method
    # @return [List of DeviceList]
    attr_accessor :devices

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :group_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :lead_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :mdn_zip_code

    # TODO: Write general description for this method
    # @return [PlaceOfUse]
    attr_accessor :primary_place_of_use

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :public_ip_restriction

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :service_plan

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :sku_number

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["account_name"] = "accountName"
        @hash["carrier_ip_pool_name"] = "carrierIpPoolName"
        @hash["carrier_name"] = "carrierName"
        @hash["cost_center_code"] = "costCenterCode"
        @hash["custom_fields"] = "customFields"
        @hash["devices"] = "devices"
        @hash["group_name"] = "groupName"
        @hash["lead_id"] = "leadId"
        @hash["mdn_zip_code"] = "mdnZipCode"
        @hash["primary_place_of_use"] = "primaryPlaceOfUse"
        @hash["public_ip_restriction"] = "publicIpRestriction"
        @hash["service_plan"] = "servicePlan"
        @hash["sku_number"] = "skuNumber"
      end
      @hash
    end

    def initialize(account_name = nil,
                   carrier_ip_pool_name = nil,
                   carrier_name = nil,
                   cost_center_code = nil,
                   custom_fields = nil,
                   devices = nil,
                   group_name = nil,
                   lead_id = nil,
                   mdn_zip_code = nil,
                   primary_place_of_use = nil,
                   public_ip_restriction = nil,
                   service_plan = nil,
                   sku_number = nil)
      @account_name = account_name
      @carrier_ip_pool_name = carrier_ip_pool_name
      @carrier_name = carrier_name
      @cost_center_code = cost_center_code
      @custom_fields = custom_fields
      @devices = devices
      @group_name = group_name
      @lead_id = lead_id
      @mdn_zip_code = mdn_zip_code
      @primary_place_of_use = primary_place_of_use
      @public_ip_restriction = public_ip_restriction
      @service_plan = service_plan
      @sku_number = sku_number
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        account_name = hash["accountName"]
        carrier_ip_pool_name = hash["carrierIpPoolName"]
        carrier_name = hash["carrierName"]
        cost_center_code = hash["costCenterCode"]
        # Parameter is an array, so we need to iterate through it
        custom_fields = nil
        if hash["customFields"] != nil
          custom_fields = Array.new
          hash["customFields"].each{|structure| custom_fields << (KvPair.from_hash(structure) if structure)}
        end
        # Parameter is an array, so we need to iterate through it
        devices = nil
        if hash["devices"] != nil
          devices = Array.new
          hash["devices"].each{|structure| devices << (DeviceList.from_hash(structure) if structure)}
        end
        group_name = hash["groupName"]
        lead_id = hash["leadId"]
        mdn_zip_code = hash["mdnZipCode"]
        primary_place_of_use = PlaceOfUse.from_hash(hash["primaryPlaceOfUse"]) if hash["primaryPlaceOfUse"]
        public_ip_restriction = hash["publicIpRestriction"]
        service_plan = hash["servicePlan"]
        sku_number = hash["skuNumber"]

        # Create object from extracted values
        CarrierActivateRequest.new(account_name,
                                   carrier_ip_pool_name,
                                   carrier_name,
                                   cost_center_code,
                                   custom_fields,
                                   devices,
                                   group_name,
                                   lead_id,
                                   mdn_zip_code,
                                   primary_place_of_use,
                                   public_ip_restriction,
                                   service_plan,
                                   sku_number)
      end
    end
  end
end
