# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ThingSpaceConnectivityManagementApi
  class CarrierInformation < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :carrier_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :service_plan

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :state

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["carrier_name"] = "carrierName"
        @hash["service_plan"] = "servicePlan"
        @hash["state"] = "state"
      end
      @hash
    end

    def initialize(carrier_name = nil,
                   service_plan = nil,
                   state = nil)
      @carrier_name = carrier_name
      @service_plan = service_plan
      @state = state
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        carrier_name = hash["carrierName"]
        service_plan = hash["servicePlan"]
        state = hash["state"]

        # Create object from extracted values
        CarrierInformation.new(carrier_name,
                               service_plan,
                               state)
      end
    end
  end
end
