# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ThingSpaceConnectivityManagementApi
  class ConnectionHistoryResponse < BaseModel
    # TODO: Write general description for this method
    # @return [List of ConnectionEvent]
    attr_accessor :connection_history

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :has_more_data

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["connection_history"] = "connectionHistory"
        @hash["has_more_data"] = "hasMoreData"
      end
      @hash
    end

    def initialize(connection_history = nil,
                   has_more_data = nil)
      @connection_history = connection_history
      @has_more_data = has_more_data
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        # Parameter is an array, so we need to iterate through it
        connection_history = nil
        if hash["connectionHistory"] != nil
          connection_history = Array.new
          hash["connectionHistory"].each{|structure| connection_history << (ConnectionEvent.from_hash(structure) if structure)}
        end
        has_more_data = hash["hasMoreData"]

        # Create object from extracted values
        ConnectionHistoryResponse.new(connection_history,
                                      has_more_data)
      end
    end
  end
end
