# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ThingSpaceConnectivityManagementApi
  class ConnectionEvent < BaseModel
    # TODO: Write general description for this method
    # @return [List of KvPair]
    attr_accessor :connection_event_attributes

    # TODO: Write general description for this method
    # @return [List of KvPair]
    attr_accessor :extended_attributes

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :occurred_at

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["connection_event_attributes"] = "connectionEventAttributes"
        @hash["extended_attributes"] = "extendedAttributes"
        @hash["occurred_at"] = "occurredAt"
      end
      @hash
    end

    def initialize(connection_event_attributes = nil,
                   extended_attributes = nil,
                   occurred_at = nil)
      @connection_event_attributes = connection_event_attributes
      @extended_attributes = extended_attributes
      @occurred_at = occurred_at
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        # Parameter is an array, so we need to iterate through it
        connection_event_attributes = nil
        if hash["connectionEventAttributes"] != nil
          connection_event_attributes = Array.new
          hash["connectionEventAttributes"].each{|structure| connection_event_attributes << (KvPair.from_hash(structure) if structure)}
        end
        # Parameter is an array, so we need to iterate through it
        extended_attributes = nil
        if hash["extendedAttributes"] != nil
          extended_attributes = Array.new
          hash["extendedAttributes"].each{|structure| extended_attributes << (KvPair.from_hash(structure) if structure)}
        end
        occurred_at = hash["occurredAt"]

        # Create object from extracted values
        ConnectionEvent.new(connection_event_attributes,
                            extended_attributes,
                            occurred_at)
      end
    end
  end
end
