# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ThingSpaceConnectivityManagementApi
  class CreateDevGroupRequest < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :account_name

    # TODO: Write general description for this method
    # @return [List of DeviceId]
    attr_accessor :devices_to_add

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :group_description

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :group_name

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["account_name"] = "accountName"
        @hash["devices_to_add"] = "devicesToAdd"
        @hash["group_description"] = "groupDescription"
        @hash["group_name"] = "groupName"
      end
      @hash
    end

    def initialize(account_name = nil,
                   devices_to_add = nil,
                   group_description = nil,
                   group_name = nil)
      @account_name = account_name
      @devices_to_add = devices_to_add
      @group_description = group_description
      @group_name = group_name
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        account_name = hash["accountName"]
        # Parameter is an array, so we need to iterate through it
        devices_to_add = nil
        if hash["devicesToAdd"] != nil
          devices_to_add = Array.new
          hash["devicesToAdd"].each{|structure| devices_to_add << (DeviceId.from_hash(structure) if structure)}
        end
        group_description = hash["groupDescription"]
        group_name = hash["groupName"]

        # Create object from extracted values
        CreateDevGroupRequest.new(account_name,
                                  devices_to_add,
                                  group_description,
                                  group_name)
      end
    end
  end
end
