# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ThingSpaceConnectivityManagementApi
  class CustomerName < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :first_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :last_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :middle_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :title

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["first_name"] = "firstName"
        @hash["last_name"] = "lastName"
        @hash["middle_name"] = "middleName"
        @hash["title"] = "title"
      end
      @hash
    end

    def initialize(first_name = nil,
                   last_name = nil,
                   middle_name = nil,
                   title = nil)
      @first_name = first_name
      @last_name = last_name
      @middle_name = middle_name
      @title = title
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        first_name = hash["firstName"]
        last_name = hash["lastName"]
        middle_name = hash["middleName"]
        title = hash["title"]

        # Create object from extracted values
        CustomerName.new(first_name,
                         last_name,
                         middle_name,
                         title)
      end
    end
  end
end
