# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ThingSpaceConnectivityManagementApi
  class DeviceListRequest < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :account_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :current_state

    # TODO: Write general description for this method
    # @return [List of KvPair]
    attr_accessor :custom_fields

    # TODO: Write general description for this method
    # @return [DeviceId]
    attr_accessor :device_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :earliest

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :group_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :latest

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :service_plan

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["account_name"] = "accountName"
        @hash["current_state"] = "currentState"
        @hash["custom_fields"] = "customFields"
        @hash["device_id"] = "deviceId"
        @hash["earliest"] = "earliest"
        @hash["group_name"] = "groupName"
        @hash["latest"] = "latest"
        @hash["service_plan"] = "servicePlan"
      end
      @hash
    end

    def initialize(account_name = nil,
                   current_state = nil,
                   custom_fields = nil,
                   device_id = nil,
                   earliest = nil,
                   group_name = nil,
                   latest = nil,
                   service_plan = nil)
      @account_name = account_name
      @current_state = current_state
      @custom_fields = custom_fields
      @device_id = device_id
      @earliest = earliest
      @group_name = group_name
      @latest = latest
      @service_plan = service_plan
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        account_name = hash["accountName"]
        current_state = hash["currentState"]
        # Parameter is an array, so we need to iterate through it
        custom_fields = nil
        if hash["customFields"] != nil
          custom_fields = Array.new
          hash["customFields"].each{|structure| custom_fields << (KvPair.from_hash(structure) if structure)}
        end
        device_id = DeviceId.from_hash(hash["deviceId"]) if hash["deviceId"]
        earliest = hash["earliest"]
        group_name = hash["groupName"]
        latest = hash["latest"]
        service_plan = hash["servicePlan"]

        # Create object from extracted values
        DeviceListRequest.new(account_name,
                              current_state,
                              custom_fields,
                              device_id,
                              earliest,
                              group_name,
                              latest,
                              service_plan)
      end
    end
  end
end
