# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ThingSpaceConnectivityManagementApi
  class DeviceListResponse < BaseModel
    # TODO: Write general description for this method
    # @return [List of Device]
    attr_accessor :devices

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :has_more_data

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["devices"] = "devices"
        @hash["has_more_data"] = "hasMoreData"
      end
      @hash
    end

    def initialize(devices = nil,
                   has_more_data = nil)
      @devices = devices
      @has_more_data = has_more_data
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        # Parameter is an array, so we need to iterate through it
        devices = nil
        if hash["devices"] != nil
          devices = Array.new
          hash["devices"].each{|structure| devices << (Device.from_hash(structure) if structure)}
        end
        has_more_data = hash["hasMoreData"]

        # Create object from extracted values
        DeviceListResponse.new(devices,
                               has_more_data)
      end
    end
  end
end
