# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ThingSpaceConnectivityManagementApi
  class DeviceUsageListResponse < BaseModel
    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :has_more_data

    # TODO: Write general description for this method
    # @return [List of Usage]
    attr_accessor :usage_history

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["has_more_data"] = "hasMoreData"
        @hash["usage_history"] = "usageHistory"
      end
      @hash
    end

    def initialize(has_more_data = nil,
                   usage_history = nil)
      @has_more_data = has_more_data
      @usage_history = usage_history
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        has_more_data = hash["hasMoreData"]
        # Parameter is an array, so we need to iterate through it
        usage_history = nil
        if hash["usageHistory"] != nil
          usage_history = Array.new
          hash["usageHistory"].each{|structure| usage_history << (Usage.from_hash(structure) if structure)}
        end

        # Create object from extracted values
        DeviceUsageListResponse.new(has_more_data,
                                    usage_history)
      end
    end
  end
end
