# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ThingSpaceConnectivityManagementApi
  class DeviceAggregateUsageListRequest < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :account_name

    # TODO: Write general description for this method
    # @return [List of DeviceId]
    attr_accessor :device_ids

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :end_time

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :group_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :start_time

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["account_name"] = "accountName"
        @hash["device_ids"] = "deviceIds"
        @hash["end_time"] = "endTime"
        @hash["group_name"] = "groupName"
        @hash["start_time"] = "startTime"
      end
      @hash
    end

    def initialize(account_name = nil,
                   device_ids = nil,
                   end_time = nil,
                   group_name = nil,
                   start_time = nil)
      @account_name = account_name
      @device_ids = device_ids
      @end_time = end_time
      @group_name = group_name
      @start_time = start_time
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        account_name = hash["accountName"]
        # Parameter is an array, so we need to iterate through it
        device_ids = nil
        if hash["deviceIds"] != nil
          device_ids = Array.new
          hash["deviceIds"].each{|structure| device_ids << (DeviceId.from_hash(structure) if structure)}
        end
        end_time = hash["endTime"]
        group_name = hash["groupName"]
        start_time = hash["startTime"]

        # Create object from extracted values
        DeviceAggregateUsageListRequest.new(account_name,
                                            device_ids,
                                            end_time,
                                            group_name,
                                            start_time)
      end
    end
  end
end
