# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ThingSpaceConnectivityManagementApi
  class GroupResponse < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :description

    # TODO: Write general description for this method
    # @return [List of KvPair]
    attr_accessor :extended_attributes

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :is_default_group

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :name

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["description"] = "description"
        @hash["extended_attributes"] = "extendedAttributes"
        @hash["is_default_group"] = "isDefaultGroup"
        @hash["name"] = "name"
      end
      @hash
    end

    def initialize(description = nil,
                   extended_attributes = nil,
                   is_default_group = nil,
                   name = nil)
      @description = description
      @extended_attributes = extended_attributes
      @is_default_group = is_default_group
      @name = name
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        description = hash["description"]
        # Parameter is an array, so we need to iterate through it
        extended_attributes = nil
        if hash["extendedAttributes"] != nil
          extended_attributes = Array.new
          hash["extendedAttributes"].each{|structure| extended_attributes << (KvPair.from_hash(structure) if structure)}
        end
        is_default_group = hash["isDefaultGroup"]
        name = hash["name"]

        # Create object from extracted values
        GroupResponse.new(description,
                          extended_attributes,
                          is_default_group,
                          name)
      end
    end
  end
end
