# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ThingSpaceConnectivityManagementApi
  class KvPair < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :key

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :value

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["key"] = "key"
        @hash["value"] = "value"
      end
      @hash
    end

    def initialize(key = nil,
                   value = nil)
      @key = key
      @value = value
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        key = hash["key"]
        value = hash["value"]

        # Create object from extracted values
        KvPair.new(key,
                   value)
      end
    end
  end
end
