# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ThingSpaceConnectivityManagementApi
  class LeadResponse < BaseModel
    # TODO: Write general description for this method
    # @return [Address]
    attr_accessor :address

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :lead_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :lead_state

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["address"] = "address"
        @hash["lead_id"] = "leadId"
        @hash["lead_state"] = "leadState"
      end
      @hash
    end

    def initialize(address = nil,
                   lead_id = nil,
                   lead_state = nil)
      @address = address
      @lead_id = lead_id
      @lead_state = lead_state
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        address = Address.from_hash(hash["address"]) if hash["address"]
        lead_id = hash["leadId"]
        lead_state = hash["leadState"]

        # Create object from extracted values
        LeadResponse.new(address,
                         lead_id,
                         lead_state)
      end
    end
  end
end
