# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ThingSpaceConnectivityManagementApi
  class LeadInformationResponse < BaseModel
    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :has_more_data

    # TODO: Write general description for this method
    # @return [List of LeadResponse]
    attr_accessor :leads

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["has_more_data"] = "hasMoreData"
        @hash["leads"] = "leads"
      end
      @hash
    end

    def initialize(has_more_data = nil,
                   leads = nil)
      @has_more_data = has_more_data
      @leads = leads
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        has_more_data = hash["hasMoreData"]
        # Parameter is an array, so we need to iterate through it
        leads = nil
        if hash["leads"] != nil
          leads = Array.new
          hash["leads"].each{|structure| leads << (LeadResponse.from_hash(structure) if structure)}
        end

        # Create object from extracted values
        LeadInformationResponse.new(has_more_data,
                                    leads)
      end
    end
  end
end
