# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ThingSpaceConnectivityManagementApi
  class LogInResponse < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :session_token

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["session_token"] = "sessionToken"
      end
      @hash
    end

    def initialize(session_token = nil)
      @session_token = session_token
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        session_token = hash["sessionToken"]

        # Create object from extracted values
        LogInResponse.new(session_token)
      end
    end
  end
end
