# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ThingSpaceConnectivityManagementApi
  class LogInRequest < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :username

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :password

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["username"] = "username"
        @hash["password"] = "password"
      end
      @hash
    end

    def initialize(username = nil,
                   password = nil)
      @username = username
      @password = password
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        username = hash["username"]
        password = hash["password"]

        # Create object from extracted values
        LogInRequest.new(username,
                         password)
      end
    end
  end
end
