# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ThingSpaceConnectivityManagementApi
  class ProvisioningHistory < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :event_by

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :event_type

    # TODO: Write general description for this method
    # @return [List of KvPair]
    attr_accessor :extended_attributes

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :mdn

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :msisdn

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :occurred_at

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :service_plan

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :status

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["event_by"] = "eventBy"
        @hash["event_type"] = "eventType"
        @hash["extended_attributes"] = "extendedAttributes"
        @hash["mdn"] = "mdn"
        @hash["msisdn"] = "msisdn"
        @hash["occurred_at"] = "occurredAt"
        @hash["service_plan"] = "servicePlan"
        @hash["status"] = "status"
      end
      @hash
    end

    def initialize(event_by = nil,
                   event_type = nil,
                   extended_attributes = nil,
                   mdn = nil,
                   msisdn = nil,
                   occurred_at = nil,
                   service_plan = nil,
                   status = nil)
      @event_by = event_by
      @event_type = event_type
      @extended_attributes = extended_attributes
      @mdn = mdn
      @msisdn = msisdn
      @occurred_at = occurred_at
      @service_plan = service_plan
      @status = status
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        event_by = hash["eventBy"]
        event_type = hash["eventType"]
        # Parameter is an array, so we need to iterate through it
        extended_attributes = nil
        if hash["extendedAttributes"] != nil
          extended_attributes = Array.new
          hash["extendedAttributes"].each{|structure| extended_attributes << (KvPair.from_hash(structure) if structure)}
        end
        mdn = hash["mdn"]
        msisdn = hash["msisdn"]
        occurred_at = hash["occurredAt"]
        service_plan = hash["servicePlan"]
        status = hash["status"]

        # Create object from extracted values
        ProvisioningHistory.new(event_by,
                                event_type,
                                extended_attributes,
                                mdn,
                                msisdn,
                                occurred_at,
                                service_plan,
                                status)
      end
    end
  end
end
