# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ThingSpaceConnectivityManagementApi
  class RegisterCallbackRequest < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :url

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :username

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :password

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["name"] = "name"
        @hash["url"] = "url"
        @hash["username"] = "username"
        @hash["password"] = "password"
      end
      @hash
    end

    def initialize(name = nil,
                   url = nil,
                   username = nil,
                   password = nil)
      @name = name
      @url = url
      @username = username
      @password = password
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        name = hash["name"]
        url = hash["url"]
        username = hash["username"]
        password = hash["password"]

        # Create object from extracted values
        RegisterCallbackRequest.new(name,
                                    url,
                                    username,
                                    password)
      end
    end
  end
end
