# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ThingSpaceConnectivityManagementApi
  class RequestResponse < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :request_id

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["request_id"] = "requestId"
      end
      @hash
    end

    def initialize(request_id = nil)
      @request_id = request_id
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        request_id = hash["requestId"]

        # Create object from extracted values
        RequestResponse.new(request_id)
      end
    end
  end
end
