# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ThingSpaceConnectivityManagementApi
  class SessionResetPasswordRequest < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :old_password

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["old_password"] = "oldPassword"
      end
      @hash
    end

    def initialize(old_password = nil)
      @old_password = old_password
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        old_password = hash["oldPassword"]

        # Create object from extracted values
        SessionResetPasswordRequest.new(old_password)
      end
    end
  end
end
