# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ThingSpaceConnectivityManagementApi
  class SessionResetPasswordResponse < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :new_password

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["new_password"] = "newPassword"
      end
      @hash
    end

    def initialize(new_password = nil)
      @new_password = new_password
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        new_password = hash["newPassword"]

        # Create object from extracted values
        SessionResetPasswordResponse.new(new_password)
      end
    end
  end
end
