# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module ThingSpaceConnectivityManagementApi
  class SmsMessagesResponse < BaseModel
    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :has_more_data

    # TODO: Write general description for this method
    # @return [List of SmsMessage]
    attr_accessor :messages

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["has_more_data"] = "hasMoreData"
        @hash["messages"] = "messages"
      end
      @hash
    end

    def initialize(has_more_data = nil,
                   messages = nil)
      @has_more_data = has_more_data
      @messages = messages
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        has_more_data = hash["hasMoreData"]
        # Parameter is an array, so we need to iterate through it
        messages = nil
        if hash["messages"] != nil
          messages = Array.new
          hash["messages"].each{|structure| messages << (SmsMessage.from_hash(structure) if structure)}
        end

        # Create object from extracted values
        SmsMessagesResponse.new(has_more_data,
                                messages)
      end
    end
  end
end
